QLNS/Controllers/HopDongController.cs
using QLNS.Models.entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLNS.Controllers
{
    public class HopDongController : Controller
    {
        // GET: HopDong
        QuanLiNhanSu ql = new QuanLiNhanSu();

        public ActionResult Index()
        {
            return View(ql.HopDongs.ToList());
        }
        public ActionResult ThemMoi()
        {
            //Đưa dữ liệu vào dropdownlist

            ViewBag.MaNV = new SelectList(ql.NhanViens.ToList().OrderBy(n => n.MaNV), "MaNV","HoTen");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(HopDong hd, HttpPostedFileBase fileUpload)
        {


            //Đưa dữ liệu vào dropdownlist

            //kiểm tra đường dẫn ảnh bìa
            ViewBag.MaNV = new SelectList(ql.NhanViens.ToList().OrderBy(n => n.MaNV), "MaNV", "HoTen");
            //Thêm vào cơ sở dữ liệu
            {
                ql.HopDongs.Add(hd);
                ql.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult ChinhSua(string Mapb)
        {
            //Lấy ra đối tượng sách theo mã 
            PhongBan pb = ql.PhongBans.SingleOrDefault(n => n.MaPB == Mapb);
            if (pb == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Đưa dữ liệu vào dropdownlist

            return View(pb);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(PhongBan pb, HttpPostedFileBase fileUpload)
        {


            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                //Lưu tên file

                //sp.HinhAnh = fileUpload.FileName;
                ql.PhongBans.Add(pb);
                //Thực hiện cập nhận trong model
                ql.Entry(pb).State = System.Data.Entity.EntityState.Modified;
                ql.SaveChanges();

            }
            return RedirectToAction("Index");
            //return View();
        }


        //Hiển thị sản phẩm
        public ActionResult HienThi(string Mapb)
        {
            //Lấy ra đối tượng sách theo mã 
            PhongBan pb = ql.PhongBans.SingleOrDefault(n => n.MaPB == Mapb);
            if (pb == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(pb);
        }
        [HttpGet]
        public ActionResult Xoa(string Mahd)
        {
            //Lấy ra đối tượng sách theo mã 
            HopDong hd = ql.HopDongs.SingleOrDefault(n => n.MaHD == Mahd);
            if (hd == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(hd);
        }
        [HttpPost, ActionName("Xoa")]

        public ActionResult XacNhanXoa(string Mahd)
        {
            HopDong hd = ql.HopDongs.SingleOrDefault(n => n.MaHD == Mahd);
            if (hd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ql.HopDongs.Remove(hd);
            ql.SaveChanges();
            return RedirectToAction("Index");

        }

        [HttpPost]
        public ActionResult KetQuaTimKiem(FormCollection f, int? page)
        {
            string sTuKhoa = f["timkiem"].ToString();
            ViewBag.TuKhoa = sTuKhoa;
            List<HopDong> lstKQTK = ql.HopDongs.Where(n => n.NhanVien.HoTen.Contains(sTuKhoa)).ToList();
            //Phân trang

            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào";
                return View(ql.HopDongs.OrderBy(n => n.NhanVien.HoTen));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
            return View(lstKQTK.OrderBy(n => n.NhanVien.HoTen));
        }
        [HttpGet]
        public ActionResult KetQuaTimKiem(int? page, string sTuKhoa)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<HopDong> lstKQTK = ql.HopDongs.Where(n => n.NhanVien.HoTen.Contains(sTuKhoa)).ToList();
            //Phân trang

            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy hợp đồng nào";
                return View(ql.HopDongs.OrderBy(n => n.NhanVien.HoTen));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
            return View(lstKQTK.OrderBy(n => n.NhanVien.HoTen));
        }
    }
}

QLNS/Controllers/LoginController.cs
using Models;
using QLNS.Controllers.code;
using QLNS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLNS.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(LoginModel model)
        {
            var result = new AccountModel().Login(model.Nameaccount, model.Password);
            if(result&& ModelState.IsValid)
            
            {
                SessionHelper.SetSession(new UserSession() { Taikhoan = model.Nameaccount });
                return RedirectToAction("Index", "NhanVien");
            }
            else
            {
                ModelState.AddModelError("", "Tên đăng nhập hoặc mật khẩu không đúng");

            }
            return View(model);
        }
    }
}

QLNS/Controllers/NguoiDungController.cs
using QLNS.Models.entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLNS.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        QuanLiNhanSu ql = new QuanLiNhanSu();

        public ActionResult Index()
        {
            return View(ql.Accounts.ToList());
        }
        public ActionResult ThemMoi()
        {
            //Đưa dữ liệu vào dropdownlist


            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(Account nd, HttpPostedFileBase fileUpload)
        {
            //Đưa dữ liệu vào dropdownlist

            //kiểm tra đường dẫn ảnh bìa

            //Thêm vào cơ sở dữ liệu
            {

                ql.Accounts.Add(nd);
                ql.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult ChinhSua(string tkhoan)
        {
            //Lấy ra đối tượng sách theo mã 
            Account nd = ql.Accounts.SingleOrDefault(n => n.Nameaccount == tkhoan);
            if (nd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Đưa dữ liệu vào dropdownlist

            return View(nd);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(Account nd, HttpPostedFileBase fileUpload)
        {

            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                //Lưu tên file

                //sp.HinhAnh = fileUpload.FileName;
                ql.Accounts.Add(nd);
                //Thực hiện cập nhận trong model
                ql.Entry(nd).State = System.Data.Entity.EntityState.Modified;
                ql.SaveChanges();

            }
            return RedirectToAction("Index");
            //return View();
        }


        //Hiển thị sản phẩm
        public ActionResult HienThi(string Mapb)
        {
            //Lấy ra đối tượng sách theo mã 
            PhongBan pb = ql.PhongBans.SingleOrDefault(n => n.MaPB == Mapb);
            if (pb == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(pb);
        }
        [HttpGet]
        public ActionResult Xoa(string tkhoan)
        {
            //Lấy ra đối tượng sách theo mã 
            Account nd = ql.Accounts.SingleOrDefault(n => n.Nameaccount == tkhoan);
            if (nd == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(nd);
        }
        [HttpPost, ActionName("Xoa")]

        public ActionResult XacNhanXoa(string tkhoan)
        {
            Account nd = ql.Accounts.SingleOrDefault(n => n.Nameaccount == tkhoan);
            if (nd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ql.Accounts.Remove(nd);
            ql.SaveChanges();
            return RedirectToAction("Index");

        }

        [HttpPost]
        public ActionResult KetQuaTimKiem(FormCollection f, int? page)
        {
            string sTuKhoa = f["timkiem"].ToString();
            ViewBag.TuKhoa = sTuKhoa;
            List<Account> lstKQTK = ql.Accounts.Where(n => n.Nameaccount.Contains(sTuKhoa)).ToList();
            //Phân trang

            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy người dùng nào";
                return View(ql.Accounts.OrderBy(n => n.Nameaccount));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
            return View(lstKQTK.OrderBy(n => n.Nameaccount));
        }
        [HttpGet]
        public ActionResult KetQuaTimKiem(int? page, string sTuKhoa)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<Account> lstKQTK = ql.Accounts.Where(n => n.Nameaccount.Contains(sTuKhoa)).ToList();
            //Phân trang

            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy người dùng nào";
                return View(ql.Accounts.OrderBy(n => n.Nameaccount));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
            return View(lstKQTK.OrderBy(n => n.Nameaccount));
        }
    }
}

QLNS/Controllers/PhongBanController.cs
using QLNS.Models.entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLNS.Controllers
{
    public class PhongBanController : Controller
    {
        // GET: PhongBan
        QuanLiNhanSu ql = new QuanLiNhanSu();

        public ActionResult Index()
        {
            return View(ql.PhongBans.ToList());
        }
        public ActionResult ThemMoi()
        {
            //Đưa dữ liệu vào dropdownlist
            

            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(PhongBan pb, HttpPostedFileBase fileUpload)
        {


            //Đưa dữ liệu vào dropdownlist
           
            //kiểm tra đường dẫn ảnh bìa

            //Thêm vào cơ sở dữ liệu
            {
                
                ql.PhongBans.Add(pb);
                ql.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult ChinhSua(string Mapb)
        {
            //Lấy ra đối tượng sách theo mã 
            PhongBan pb = ql.PhongBans.SingleOrDefault(n => n.MaPB == Mapb);
            if (pb == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Đưa dữ liệu vào dropdownlist
            
            return View(pb);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(PhongBan pb, HttpPostedFileBase fileUpload)
        {
            

            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                //Lưu tên file

                //sp.HinhAnh = fileUpload.FileName;
                ql.PhongBans.Add(pb);
                //Thực hiện cập nhận trong model
                ql.Entry(pb).State = System.Data.Entity.EntityState.Modified;
                ql.SaveChanges();

            }
            return RedirectToAction("Index");
            //return View();
        }


        //Hiển thị sản phẩm
        public ActionResult HienThi(string Mapb)
        {
            //Lấy ra đối tượng sách theo mã 
            PhongBan pb = ql.PhongBans.SingleOrDefault(n => n.MaPB == Mapb);
            if (pb == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(pb);
        }
        [HttpGet]
        public ActionResult Xoa(string Mapb)
        {
            //Lấy ra đối tượng sách theo mã 
            PhongBan pb = ql.PhongBans.SingleOrDefault(n => n.MaPB == Mapb);
            if (pb == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(pb);
        }
        [HttpPost, ActionName("Xoa")]

        public ActionResult XacNhanXoa(string Mapb)
        {
            PhongBan pb = ql.PhongBans.SingleOrDefault(n => n.MaPB == Mapb);
            if (pb == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ql.PhongBans.Remove(pb);
            ql.SaveChanges();
            return RedirectToAction("Index");

        }
        
        [HttpPost]
        public ActionResult KetQuaTimKiem(FormCollection f, int? page)
        {
            string sTuKhoa = f["timkiem"].ToString();
            ViewBag.TuKhoa = sTuKhoa;
            List<PhongBan> lstKQTK = ql.PhongBans.Where(n => n.TenPb.Contains(sTuKhoa)).ToList();
            //Phân trang

            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào";
                return View(ql.PhongBans.OrderBy(n => n.TenPb));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
            return View(lstKQTK.OrderBy(n => n.TenPb));
        }
        [HttpGet]
        public ActionResult KetQuaTimKiem(int? page, string sTuKhoa)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<PhongBan> lstKQTK = ql.PhongBans.Where(n => n.TenPb.Contains(sTuKhoa)).ToList();
            //Phân trang

            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào";
                return View(ql.PhongBans.OrderBy(n => n.TenPb));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
            return View(lstKQTK.OrderBy(n => n.TenPb));
        }
    }
}

QLNS/Views/Shared/QLNS.cshtml
@{
    ViewBag.Title = "QLNS";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Phần mềm quản lý nhân sự</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<link rel="stylesheet" href="css/bootstrap.min.css" />*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="css/bootstrap-responsive.min.css" />*@
    <link href="~/Content/css/bootstrap-responsive.min.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="css/fullcalendar.css" />*@
    <link href="~/Content/css/fullcalendar.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="css/matrix-style.css" />*@
    <link href="~/Content/css/matrix-style.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="css/matrix-media.css" />*@
    <link href="~/Content/css/matrix-media.css" rel="stylesheet" />
    @*<link href="font-awesome/css/font-awesome.css" rel="stylesheet" />*@
    <link href="~/Content/font/css/font-awesome.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="css/jquery.gritter.css" />*@
    <link href="~/Content/css/jquery.gritter.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
</head>
<body>

    <!--Header-part-->
    <div id="header">
        <h1><a href="dashboard.html">Matrix Admin</a></h1>
    </div>
    <!--close-Header-part-->
    <!--top-Header-menu-->
    <div id="user-nav" class="navbar navbar-inverse">
        <ul class="nav">
            <li class="dropdown" id="profile-messages">
                <a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text">Welcome User</span><b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><i class="icon-user"></i> My Profile</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-check"></i> My Tasks</a></li>
                    <li class="divider"></li>
                    <li><a href="@Url.Action("Index","Login")"><i class="icon-key"></i> Log Out</a></li>
                </ul>
            </li>
            @*<li class="dropdown" id="menu-messages">
                    <a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="icon icon-envelope"></i> <span class="text">Messages</span> <span class="label label-important">5</span> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a class="sAdd" title="" href="#"><i class="icon-plus"></i> new message</a></li>
                        <li class="divider"></li>
                        <li><a class="sInbox" title="" href="#"><i class="icon-envelope"></i> inbox</a></li>
                        <li class="divider"></li>
                        <li><a class="sOutbox" title="" href="#"><i class="icon-arrow-up"></i> outbox</a></li>
                        <li class="divider"></li>
                        <li><a class="sTrash" title="" href="#"><i class="icon-trash"></i> trash</a></li>
                    </ul>
                </li>
                <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>*@
            @*<li class=""><a title="" href="login.html"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>*@
        </ul>
    </div>
    <!--close-top-Header-menu-->
    <!--start-top-serch-->
    <!--close-top-serch-->
    <!--sidebar-menu-->
    <div id="sidebar">
        <a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
        <ul>
            <li class="submenu">
                <a href="@Url.Action("Index","NhanVien")"><i class="icon icon-th-list"></i> <span>Quản lý nhân viên</span> @*<span class="label label-important">3</span>*@</a>

                <ul>
                    @Html.Action("TheoPhongBan", "NhanVien")

                </ul>
            </li>
            <li class="submenu">
                <a href="@Url.Action("Index","PhongBan")"><i class="icon icon-th-list"></i> <span>Quản lý Phòng Ban</span> @*<span class="label label-important">3</span>*@</a>

                <ul>
                    <li><a href="@Url.Action("Index","PhongBan")">Danh sách phòng ban</a></li>
                    <li><a href="@Url.Action("ThemMoi","PhongBan")">Thêm mới phòng ban</a></li>

                </ul>
            </li>
            <li class="submenu">
                <a href="@Url.Action("Index","NguoiDung")"><i class="icon icon-th-list"></i> <span>Quản lý Người Dùng</span> @*<span class="label label-important">3</span>*@</a>

                <ul>
                    <li><a href="@Url.Action("Index","NguoiDung")">Danh sách người dùng</a></li>
                    <li><a href="@Url.Action("ThemMoi","NguoiDung")">Thêm mới người dùng</a></li>

                </ul>
            </li>
            <li class="submenu">
                <a href="@Url.Action("Index","HopDong")"><i class="icon icon-th-list"></i> <span>Quản lý Hợp Đồng</span> @*<span class="label label-important">3</span>*@</a>

                <ul>
                    <li><a href="@Url.Action("Index","HopDong")">Danh sách hợp đồng</a></li>
                    <li><a href="@Url.Action("ThemMoi","HopDong")">Thêm mới hợp đồng</a></li>

                </ul>
            </li>
            @*<li> <a href="charts.html"><i class="icon icon-signal"></i> <span>Charts &amp; graphs</span></a> </li>*@
            @*<li> <a href="widgets.html"><i class="icon icon-inbox"></i> <span>Widgets</span></a> </li>
        <li><a href="tables.html"><i class="icon icon-th"></i> <span>Tables</span></a></li>
        <li><a href="grid.html"><i class="icon icon-fullscreen"></i> <span>Full width</span></a></li>

        <li><a href="buttons.html"><i class="icon icon-tint"></i> <span>Buttons &amp; icons</span></a></li>
        <li><a href="interface.html"><i class="icon icon-pencil"></i> <span>Eelements</span></a></li>
        <li class="submenu">
            <a href="#"><i class="icon icon-file"></i> <span>Addons</span> <span class="label label-important">5</span></a>
            <ul>
                <li><a href="index2.html">Dashboard2</a></li>
                <li><a href="gallery.html">Gallery</a></li>
                <li><a href="calendar.html">Calendar</a></li>
                <li><a href="invoice.html">Invoice</a></li>
                <li><a href="chat.html">Chat option</a></li>
            </ul>
        </li>
        <li class="submenu">
            <a href="#"><i class="icon icon-info-sign"></i> <span>Error</span> <span class="label label-important">4</span></a>
            <ul>
                <li><a href="error403.html">Error 403</a></li>
                <li><a href="error404.html">Error 404</a></li>
                <li><a href="error405.html">Error 405</a></li>
                <li><a href="error500.html">Error 500</a></li>
            </ul>
        </li>*@

        </ul>
    </div>
    <!--sidebar-menu-->
    <!--main-container-part-->
    <div id="content">
        <!--breadcrumbs-->
        <div id="content-header">
            <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a></div>
        </div>
        <!--End-breadcrumbs-->
        <!--Action boxes-->
        <!--End-Action boxes-->
        <div>
            @RenderBody()

        </div>
        <!--Chart-box-->
        <!--End-Chart-box-->
        <!--end-Footer-part-->
        @*<script src="js/excanvas.min.js"></script>
        <script src="~/Scripts/JS/excanvas.min.js"></script>
        @*<script src="js/jquery.min.js"></script>*@
        <script src="~/Scripts/JS/jquery.min.js"></script>
        @*<script src="js/jquery.ui.custom.js"></script>*@
        <script src="~/Scripts/JS/jquery.ui.custom.js"></script>
        @*<script src="js/bootstrap.min.js"></script>*@
        <script src="~/Scripts/JS/bootstrap.min.js"></script>
        @*<script src="js/jquery.flot.min.js"></script>*@
        <script src="~/Scripts/JS/jquery.flot.min.js"></script>
        @*<script src="js/jquery.flot.resize.min.js"></script>*@
        <script src="~/Scripts/JS/jquery.flot.resize.min.js"></script>
        @*<script src="js/jquery.peity.min.js"></script>*@
        <script src="~/Scripts/JS/jquery.peity.min.js"></script>
        @*<script src="js/fullcalendar.min.js"></script>*@
        <script src="~/Scripts/JS/fullcalendar.min.js"></script>
        @*<script src="js/matrix.js"></script>*@
        <script src="~/Scripts/JS/matrix.js"></script>
        @*<script src="js/matrix.dashboard.js"></script>*@
        <script src="~/Scripts/JS/matrix.dashboard.js"></script>
        @*<script src="js/jquery.gritter.min.js"></script>*@
        <script src="~/Scripts/JS/jquery.gritter.min.js"></script>
        @*<script src="js/matrix.interface.js"></script>*@
        <script src="~/Scripts/JS/matrix.interface.js"></script>
        @*<script src="js/matrix.chat.js"></script>*@
        <script src="~/Scripts/JS/matrix.charts.js"></script>
        @*<script src="js/jquery.validate.js"></script>
            <script src="js/matrix.form_validation.js"></script>
            <script src="js/jquery.wizard.js"></script>
            <script src="js/jquery.uniform.js"></script>
            <script src="js/select2.min.js"></script>
            <script src="js/matrix.popover.js"></script>
            <script src="js/jquery.dataTables.min.js"></script>
            <script src="js/matrix.tables.js"></script>*@
        <script src="~/Scripts/JS/jquery.validate.js"></script>
        <script src="~/Scripts/JS/matrix.form_validation.js"></script>
        <script src="~/Scripts/JS/jquery.wizard.js"></script>
        <script src="~/Scripts/JS/jquery.uniform.js"></script>
        <script src="~/Scripts/JS/select2.min.js"></script>
        <script src="~/Scripts/JS/matrix.popover.js"></script>
        <script src="~/Scripts/JS/jquery.dataTables.min.js"></script>
        <script src="~/Scripts/JS/matrix.tables.js"></script>

        <script type="text/javascript">
            // This function is called from the pop-up menus to transfer to
            // a different page. Ignore if the value returned is a null string:
            function goPage(newURL) {

                // if url is empty, skip the menu dividers and reset the menu selection to default
                if (newURL != "") {

                    // if url is "-", it is this page -- reset the menu:
                    if (newURL == "-") {
                        resetMenu();
                    }
                    // else, send page to designated URL
                    else {
                        document.location.href = newURL;
                    }
                }
            }

            // resets the menu selection upon entry to this page:
            function resetMenu() {
                document.gomenu.selector.selectedIndex = 2;
            }
        </script>


</body>
</html>

QLNS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>